<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = array();

// cloud plugins

$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['insert_link'] = 'Link zur Nachricht einfügen';
$labels['download_and_attach'] = 'Herunterladen und anhängen';

$labels['sidebar'] = 'Sidebar';
$labels['sidebar_items'] = 'Sidebar Elemente';
$labels['sidebar_change_order'] = 'Drag & Drop Sidebar Elemente, um ihre Reihenfolge zu ändern.';

$labels['buy_now'] = 'Kaufe jetzt';
$labels['preview'] = 'Vorschau';

$labels['apps'] = 'Apps';
$labels['sidebar'] = 'Sidebar';
$labels['plugin_xbackground'] = 'Hintergrund';
$labels['plugin_xcalendar'] = 'Kalender';
$labels['plugin_xdropbox'] = 'DropBox';
$labels['plugin_xgoogle_drive'] = 'Google Drive';
$labels['plugin_xlast_login'] = 'Letzter Login';
$labels['plugin_xquote'] = 'Tägliches Angebot';
$labels['plugin_xnews_feed'] = 'News Feed';
$labels['plugin_xsignature'] = 'Signatur';
$labels['plugin_xskin'] = 'Skins';
$labels['plugin_xvertical_preview'] = 'Vertikale Vorschau';
$labels['plugin_xweather'] = 'Wetter';