<?php
/**
 * Roundcube Plus Framework plugin.
 *
 * Copyright 2016, Tecorama LLC.
 *
 * @license Commercial. See the LICENSE file for details.
 */

$labels = array();

// cloud plugins

$labels['xdropbox_name'] = 'Dropbox';
$labels['xgoogle_drive_name'] = 'Google Drive';
$labels['xwebdav_name'] = 'Cloud';
$labels['insert_link'] = 'Insert link to message';
$labels['download_and_attach'] = 'Download and attach';

$labels['sidebar'] = 'Sidebar';
$labels['sidebar_items'] = 'Sidebar items';
$labels['sidebar_change_order'] = 'Drag and drop sidebar items to change their order.';

$labels['buy_now'] = 'Buy now';
$labels['preview'] = 'Preview';

$labels['apps'] = 'Apps';
$labels['sidebar'] = 'Sidebar';
$labels['hide'] = 'Hide';
$labels['plugin_xbackground'] = 'Background';
$labels['plugin_xcalendar'] = 'Calendar';
$labels['plugin_xdropbox'] = 'DropBox';
$labels['plugin_xgoogle_drive'] = 'Google Drive';
$labels['plugin_xlast_login'] = 'Last Login';
$labels['plugin_xquote'] = 'Daily Quote';
$labels['plugin_xnews_feed'] = 'News Feed';
$labels['plugin_xsignature'] = 'Signature';
$labels['plugin_xskin'] = 'Skins';
$labels['plugin_xvertical_preview'] = 'Vertical Preview';
$labels['plugin_xweather'] = 'Weather';
$labels['plugin_xtag'] = 'Tag Manager';
$labels['plugin_xemail_schedule'] = 'Email Schedule';

$labels['invalid_image_extension'] = "Invalid image extension. The allowed extensions are: jpg, jpeg, png, gif.";
$labels['invalid_image_format'] = "This file is not a valid image.";