<?php

$labels = array();

# NEW
$labels['xdropbox_name'] = 'Dropbox';

# NEW
$labels['xgoogle_drive_name'] = 'Google Drive';

# NEW
$labels['insert_link'] = 'Insérer un lien vers le message';

# NEW
$labels['download_and_attach'] = 'Télécharger et joindre';

# NEW
$labels['sidebar'] = 'Barre latérale';

# NEW
$labels['sidebar_items'] = 'Éléments de la barre latérale';

# NEW
$labels['sidebar_change_order'] = 'Faites glisser et déposez les éléments de la barre latérale pour modifier leur ordre.';

# NEW
$labels['buy_now'] = 'Acheter maintenant';

# NEW
$labels['preview'] = 'Aperçu';

# NEW
$labels['apps'] = 'Apps';

# NEW
$labels['hide'] = 'Cacher';

# NEW
$labels['plugin_xbackground'] = 'Arrière-plan';

# NEW
$labels['plugin_xcalendar'] = 'Agenda';

# NEW
$labels['plugin_xdropbox'] = 'DropBox';

# NEW
$labels['plugin_xgoogle_drive'] = 'Google Drive';

# NEW
$labels['plugin_xlast_login'] = 'Dernière connexion';

# NEW
$labels['plugin_xquote'] = 'Citation quotidienne';

# NEW
$labels['plugin_xnews_feed'] = 'Fil d\'actualité';

# NEW
$labels['plugin_xsignature'] = 'Signature';

# NEW
$labels['plugin_xskin'] = 'Thèmes';

# NEW
$labels['plugin_xvertical_preview'] = 'Aperçu vertical';

# NEW
$labels['plugin_xweather'] = 'Météo';

# NEW
$labels['plugin_xtag'] = 'Gestionnaire de balises';

# NEW
$labels['plugin_xemail_schedule'] = 'Planification des emails';

