<?php

$labels = array();

# NEW
$labels['xdropbox_name'] = 'Dropbox';

# NEW
$labels['xgoogle_drive_name'] = 'Google Drive';

# NEW
$labels['insert_link'] = 'Wpisz link do wiadomości';

# NEW
$labels['download_and_attach'] = 'Pobierz i załącz';

# NEW
$labels['sidebar'] = 'Pasek boczny';

# NEW
$labels['sidebar_items'] = 'Obiekty na pasku bocznym';

# NEW
$labels['sidebar_change_order'] = 'Przeciągnij i upuść obiekty na pasku bocznym, aby zmienić ich kolejność.';

# NEW
$labels['buy_now'] = 'Kup teraz';

# NEW
$labels['preview'] = 'Podgląd';

# NEW
$labels['apps'] = 'Aplikacje';

# NEW
$labels['plugin_xbackground'] = 'Tło';

# NEW
$labels['plugin_xcalendar'] = 'Kalendarz';

# NEW
$labels['plugin_xdropbox'] = 'DropBox';

# NEW
$labels['plugin_xgoogle_drive'] = 'Google Drive';

# NEW
$labels['plugin_xlast_login'] = 'Ostatnie logowanie';

# NEW
$labels['plugin_xquote'] = 'Cytat Dnia';

# NEW
$labels['plugin_xnews_feed'] = 'News Feed';

# NEW
$labels['plugin_xsignature'] = 'Podpis';

# NEW
$labels['plugin_xskin'] = 'Skórki';

# NEW
$labels['plugin_xvertical_preview'] = 'Pionowy Podgląd';

# NEW
$labels['plugin_xweather'] = 'Pogoda';
