<?php

$labels = array();

# NEW
$labels['xdropbox_name'] = 'Dropbox';

# NEW
$labels['xgoogle_drive_name'] = 'Google Drive';

# NEW
$labels['insert_link'] = 'Вставить ссылку в сообщение';

# NEW
$labels['download_and_attach'] = 'загрузить и прикрепить';

# NEW
$labels['sidebar'] = 'Боковая панель';

# NEW
$labels['sidebar_items'] = 'Элементы боковой панели';

# NEW
$labels['sidebar_change_order'] = 'Перетащите элементы боковой панели, чтобы изменить их порядок.';

# NEW
$labels['buy_now'] = 'Купить сейчас';

# NEW
$labels['preview'] = 'Предварительный просмотр';

# NEW
$labels['apps'] = 'Приложения';

# NEW
$labels['hide'] = 'Спрятать';

# NEW
$labels['plugin_xbackground'] = 'Фон';

# NEW
$labels['plugin_xcalendar'] = 'Календарь';

# NEW
$labels['plugin_xdropbox'] = 'DropBox';

# NEW
$labels['plugin_xgoogle_drive'] = 'Google Drive';

# NEW
$labels['plugin_xlast_login'] = 'Последний вход';

# NEW
$labels['plugin_xquote'] = 'Ежедневная цитата';

# NEW
$labels['plugin_xnews_feed'] = 'Новостная лента';

# NEW
$labels['plugin_xsignature'] = 'Подпись';

# NEW
$labels['plugin_xskin'] = 'Скины';

# NEW
$labels['plugin_xvertical_preview'] = 'Вертикальный просмотр';

# NEW
$labels['plugin_xweather'] = 'Погода';

# NEW
$labels['plugin_xtag'] = 'Тэг менеджер';

# NEW
$labels['plugin_xemail_schedule'] = 'Расписание электронной почты';

