<?php

$labels = array();

# NEW
$labels['xdropbox_name'] = 'Dropbox';

# NEW
$labels['xgoogle_drive_name'] = 'Google Drive';

# NEW
$labels['insert_link'] = 'ставити посилання в повідомлення';

# NEW
$labels['download_and_attach'] = 'Завантаити та додати';

# NEW
$labels['sidebar'] = 'Бічна панель';

# NEW
$labels['sidebar_items'] = 'Елементи бічної панелі';

# NEW
$labels['sidebar_change_order'] = 'Перетягніть елементи бічної панелі, щоб змінити їх розташування.';

# NEW
$labels['buy_now'] = 'Придбати зараз';

# NEW
$labels['preview'] = 'Попередній перегляд';

# NEW
$labels['apps'] = 'Програми';

# NEW
$labels['hide'] = 'Приховати';

# NEW
$labels['plugin_xbackground'] = 'Фон';

# NEW
$labels['plugin_xcalendar'] = 'Календар';

# NEW
$labels['plugin_xdropbox'] = 'DropBox';

# NEW
$labels['plugin_xgoogle_drive'] = 'Google Drive';

# NEW
$labels['plugin_xlast_login'] = 'Останній вхід';

# NEW
$labels['plugin_xquote'] = 'Щодня цитата';

# NEW
$labels['plugin_xnews_feed'] = 'Стрічка новин';

# NEW
$labels['plugin_xsignature'] = 'Підпис';

# NEW
$labels['plugin_xskin'] = 'Скіни';

# NEW
$labels['plugin_xvertical_preview'] = 'Вертикальний перегляд';

# NEW
$labels['plugin_xweather'] = 'Погода';

# NEW
$labels['plugin_xtag'] = 'Тег менеджер';

# NEW
$labels['plugin_xemail_schedule'] = 'Розклад електронної пошти';

