<?php

$labels = array();

# NEW
$labels['interface_options'] = 'Options de l\'interface';

# NEW
$labels['disable_mobile_skin'] = 'Utiliser le thème bureau';

# NEW
$labels['enable_mobile_skin'] = 'Utiliser le thème mobile';

# NEW
$labels['skin_settings'] = 'Paramètres du thème';

# NEW
$labels['skin_look_and_feel'] = 'Apparence du thème';

# NEW
$labels['setting_icons'] = 'Icônes';

# NEW
$labels['icons_solid'] = 'Solide';

# NEW
$labels['icons_traditional'] = 'Traditionnel';

# NEW
$labels['icons_outlined'] = 'Contour';

# NEW
$labels['icons_material'] = 'Matière';

# NEW
$labels['icons_cartoon'] = 'Dessin';

# NEW
$labels['setting_list_icons'] = 'Icônes dans les listes';

# NEW
$labels['setting_button_icons'] = 'Icônes sur les boutons';

# NEW
$labels['setting_font_size'] = 'Taille de la police';

# NEW
$labels['font_size_xs'] = 'Le plus petit';

# NEW
$labels['font_size_s'] = 'Plus petit';

# NEW
$labels['font_size_n'] = 'Normal';

# NEW
$labels['font_size_l'] = 'Plus grand';

# NEW
$labels['font_size_xl'] = 'Le plus grand';

# NEW
$labels['setting_thick_font'] = 'Police épaisse';

# NEW
$labels['setting_font_family'] = 'Famille de police';

# NEW
$labels['setting_color'] = 'Couleur';

# NEW
$labels['save_hint'] = 'N\'oubliez pas de sauvegarder vos paramètres en cliquant sur le bouton \'Enregistrer\' ci-dessous.';

